import { Canvas, useThree, useLoader } from "@react-three/fiber";
import { CameraControls, Html } from "@react-three/drei";
import * as THREE from "three";
import { useMemo, useRef, useEffect } from "react";
// @ts-ignore
import { julian, moonposition } from "astronomia";
import SunCalc from "suncalc";
//ChatGPT Help with shaders and converting values from ra/dec/mag to xyza.
//Conversation Link:
//https://chatgpt.com/share/67ffd32e-c694-8009-b8fb-27b7b4ebda98
const vertexShader = `
  attribute float alpha;
  varying float vAlpha;

  void main() {
    vAlpha = alpha;
    vec4 mvPosition = modelViewMatrix * vec4(position, 1.0);
    gl_PointSize = 2.0;
    gl_Position = projectionMatrix * mvPosition;
  }
`;

const fragmentShader = `
  varying float vAlpha;

  void main() {
    gl_FragColor = vec4(1.0, 1.0, 1.0, vAlpha);
  }
`;

export default function NightSky({
  stars,
  time,
  lat,
  lng,
  onStarClick,
  focusedStarId,
  setFocusedStarId,
}: {
  stars: any[];
  time: Date;
  lat: number;
  lng: number;
  onStarClick: (id: string) => void;
  focusedStarId: string | null;
  setFocusedStarId: (id: string | null) => void;
}) {
  /*---------------------------------    Star Calculations    -------------------------------------*/

  //Function generated by ChatGPT: https://chatgpt.com/share/68013d8c-cb9c-8009-81e3-83b7db7676be
  function getGreenwichSiderealTimeRadians(jd: number): number {
    const T = (jd - 2451545.0) / 36525.0;

    let GMST =
      280.46061837 +
      360.98564736629 * (jd - 2451545.0) +
      0.000387933 * T * T -
      (T * T * T) / 38710000;

    GMST = ((GMST % 360) + 360) % 360; // normalize to 0–360°
    return (GMST * Math.PI) / 180; // convert to radians
  }

  //the astronomia function seems to only take in values from years, months, and days.
  //this function splits the d/m/y from the h/m/s, uses the former to get the julian from astronomia, and add the remaining time to it.
  function getJulianDateFromDate(date: Date): number {
    const year = date.getUTCFullYear();
    const month = date.getUTCMonth() + 1; // JS months are 0-based
    const day = date.getUTCDate();

    const hours = date.getUTCHours();
    const minutes = date.getUTCMinutes();
    const seconds = date.getUTCSeconds();

    //this returns the julian date as a day.
    const jd0 = julian.CalendarGregorianToJD(year, month, day);
    //as we want real time, we also need the time of the day, which is used as a decimal here.
    const timeFraction = (hours + minutes / 60 + seconds / 3600) / 24;

    return jd0 + timeFraction;
  }

  // Instead of converting every star to Alt/Az on each time change, we compute positions once
  // in equatorial coordinates (RA/Dec → XYZ on a unit sphere), then apply two group transforms:
  //   1. A fixed latitude tilt  (X-axis rotation) — only recomputes when lat changes
  //   2. A time-driven LST rotation (Y-axis rotation) — just a number, zero geometry cost
  //
  // The equatorial coordinate system places the celestial north pole at +Y, and RA=0h at +Z.
  // Rotating around Y by -LST then tilts the sphere so the observer's zenith is at the top,
  // and a further X tilt by -(90° - lat) aligns the pole correctly for the observer's latitude.

  function convertStarsToEquatorialGeometry(stars: any[], radius: number) {
    const total = stars.length;
    const positions = new Float32Array(total * 3);
    const alphas = new Float32Array(total);
    // starMap stores equatorial positions so world-space lookup works after the group rotations.
    const starMap: Record<string, [number, number, number]> = {};

    let j = 0;
    let k = 0;

    for (let i = 0; i < total; i++) {
      const star = stars[i];
      if (star.ra == null || star.dec == null || star.mag == null) continue;

      const raRad = (star.ra * 15 * Math.PI) / 180; // RA in hours → radians
      const decRad = (star.dec * Math.PI) / 180;

      // Standard equatorial → Cartesian.  RA=0 points toward +Z, pole at +Y.
      const x = radius * Math.cos(decRad) * Math.sin(raRad);
      const y = radius * Math.sin(decRad);
      const z = radius * Math.cos(decRad) * Math.cos(raRad);

      positions[j++] = x;
      positions[j++] = y;
      positions[j++] = z;

      const alpha = Math.max(0, 1 - star.mag / 4);
      alphas[k++] = alpha;

      const key = star.hip ? `HIP ${star.hip}` : null;
      if (key) {
        starMap[key] = [x, y, z];
      }
    }

    return {
      positions: positions.subarray(0, j),
      alphas: alphas.subarray(0, k),
      starMap,
    };
  }

  // Compute star geometry once — only reruns when the star list or radius changes (i.e. never during slider use).
  const { positions, alphas, starMap } = useMemo(() => {
    if (!stars?.length)
      return {
        positions: new Float32Array(),
        alphas: new Float32Array(),
        starMap: {},
      };
    return convertStarsToEquatorialGeometry(stars, 100);
  }, [stars]); // ← no more time/lat/lng here

  // LST drives the Y-rotation of the whole sphere — just arithmetic, no geometry rebuild.
  const jd = getJulianDateFromDate(new Date(time));
  const gst = getGreenwichSiderealTimeRadians(jd);
  const lst = gst + (lng * Math.PI) / 180;

  // Latitude tilt: rotate the equatorial sphere so the celestial pole sits correctly overhead.
  // At lat=90° the pole is at the zenith; at lat=0° it's on the horizon.
  const latTiltRad = ((90 - lat) * Math.PI) / 180;

  /*---------------------------------    Night Sky with Raycasting    -------------------------------------*/

  //apparently the camera function won't work unless it's contained within itself.
  //onStarClick is an external function on App.tsx.
  //Essentially just takes the nearest star.
  function StarField({
    positions,
    alphas,
    starMap,
    onStarClick,
    groupRef,
  }: {
    positions: Float32Array;
    alphas: Float32Array;
    starMap: Record<string, [number, number, number]>;
    onStarClick: (id: string) => void;
    groupRef: React.RefObject<THREE.Group>;
  }) {
    const { camera, gl } = useThree();
    const raycaster = useMemo(() => new THREE.Raycaster(), []);
    const mouse = useRef(new THREE.Vector2());

    useEffect(() => {
      //there's a slight issue when it comes to rotating the canvas,
      //and that is the event listener for clicking is detected each time, even when dragging to rotate

      let isDragging = false;

      const handleMouseDown = () => {
        isDragging = false;
      };

      const handleMouseMove = () => {
        isDragging = true;
      };

      //within the starmap data, there's essentially four objects. The xyz, and the added key.
      //The key data is based on the Hippocarus Identifier.
      //This function essentially uses raycasting in order to find the closest star the user has clicked.
      //Raycasting is akin to shooting a line within the space, where the searching algorithm finds the closest match.
      const handleClick = (event: MouseEvent) => {
        if (isDragging) return;

        //represents the box that's currently on the screen (in 2d).
        const rect = gl.domElement.getBoundingClientRect();

        //converts mouse pixel to normalised device coordinates (ndc). WebGL wants this instead of pixels.
        mouse.current.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;
        mouse.current.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;

        raycaster.setFromCamera(mouse.current, camera);

        let closestId: string | null = null;
        let closestDistance = Infinity;

        // Star positions are stored in equatorial space (local to the group).
        // To raycast against them correctly we need to transform each position into world space
        // using the group's current world matrix, which already has the LST + lat rotations applied.
        const worldMatrix = groupRef.current?.matrixWorld ?? new THREE.Matrix4();

        for (const [id, pos] of Object.entries(starMap)) {
          const point = new THREE.Vector3(...pos).applyMatrix4(worldMatrix);

          //getting the shortest distance.
          const distance = raycaster.ray.distanceToPoint(point);

          //distance tolerance.
          if (distance < 1.5 && distance < closestDistance) {
            closestDistance = distance;
            closestId = id;
          }
        }

        if (closestId) {
          onStarClick(closestId);
        }
      };

      //adding the event listeners to the renderer.
      //Them two move and downs are trackers for dragging. Should not handle the star clicking.
      gl.domElement.addEventListener("mousedown", handleMouseDown);
      gl.domElement.addEventListener("mousemove", handleMouseMove);
      gl.domElement.addEventListener("click", handleClick);

      return () => {
        gl.domElement.removeEventListener("mousedown", handleMouseDown);
        gl.domElement.removeEventListener("mousemove", handleMouseMove);
        gl.domElement.removeEventListener("click", handleClick);
      };
    }, [camera, gl, starMap, onStarClick, groupRef]);
    return (
      <>
        <points>
          <bufferGeometry>
            <primitive
              attach="attributes-position"
              object={new THREE.BufferAttribute(positions, 3)}
            />
            <primitive
              attach="attributes-alpha"
              object={new THREE.BufferAttribute(alphas, 1)}
            />
          </bufferGeometry>

          <shaderMaterial
            vertexShader={vertexShader}
            fragmentShader={fragmentShader}
            transparent
            uniforms={{
              size: { value: 3.0 },
              color: { value: new THREE.Color("white") },
            }}
          />
        </points>
      </>
    );
  }

  /*---------------------------------    Raycasting for the click interactions    -------------------------------------*/

  //Camera controls is an orbit camera, so it wasn't as easy as just setlook at :tear:
  const controlsRef = useRef<any>(null);
  // Reference to the outermost sky group so we can read its world matrix for star focus & raycasting.
  const skyGroupRef = useRef<THREE.Group>(null!) as React.RefObject<THREE.Group>;

  const goToStar = (id: string) => {
    if (!controlsRef.current || !starMap[id]) return;

    // The stored position is in equatorial (local) space — transform to world space first.
    const worldMatrix = skyGroupRef.current?.matrixWorld ?? new THREE.Matrix4();
    const starPosition = new THREE.Vector3(...starMap[id]).applyMatrix4(worldMatrix);

    const cameraEnd = controlsRef.current._sphericalEnd; //value in CameraControl. The target in the sphere space.

    const starDirection = starPosition.clone().normalize(); //normalize turns the vector values to a distance of one. This is so the camera doesn't shoot forward.

    const newCameraDirection = starDirection.clone().negate(); //orbit cameras means that we will always look towards the center. The star direction calculates it, and negating the value means we can position ourselves to see the target.

    //https://stackoverflow.com/questions/30271693/converting-between-cartesian-coordinates-and-spherical-coordinates
    //:pray:
    const targetTheta = Math.atan2(newCameraDirection.x, newCameraDirection.z);
    const targetPhi = Math.acos(newCameraDirection.y);

    cameraEnd.theta = targetTheta;
    cameraEnd.phi = targetPhi;

    controlsRef.current._needsUpdate = true; //value in CameraControl. Triggers the movement.
  };

  //if focusedStarId changes, (controlled on App.tsx) change the camera.
  useEffect(() => {
    if (focusedStarId) {
      goToStar(focusedStarId);
    }
    setFocusedStarId(null);
  }, [focusedStarId]);

  /*---------------------------------    Moon Mapping    -------------------------------------*/

  function getMoonTextureIndex(phase: number): number {
    if (phase < 0.03 || phase > 0.97) return 0;
    if (phase < 0.22) return 1;
    if (phase < 0.28) return 2;
    if (phase < 0.47) return 3;
    if (phase < 0.53) return 4;
    if (phase < 0.72) return 5;
    if (phase < 0.78) return 6;
    return 7;
  }
  const moonIllum = SunCalc.getMoonIllumination(time);
  const moonIndex = getMoonTextureIndex(moonIllum.phase);
  const moonTexture = useLoader(THREE.TextureLoader, `/moon_${moonIndex}.svg`);

  const moonCoords = moonposition.position(jd);
  const moonRaRad = moonCoords.ra;
  const moonDecRad = moonCoords.dec;

  // Moon lives inside the rotation groups, so store it in equatorial coordinates just like the stars.
  // The lat-tilt + LST rotations will position it correctly without any extra conversion.
  const moonX = 100 * Math.cos(moonDecRad) * Math.sin(moonRaRad);
  const moonY = 100 * Math.sin(moonDecRad);
  const moonZ = 100 * Math.cos(moonDecRad) * Math.cos(moonRaRad);

  return (
    <>
      <Canvas
        camera={{ position: [0, 1, 3] }}
        style={{ width: "100vw", height: "100vh" }}
      >
        <ambientLight intensity={0.5} />
        {/*---------------------------------   Star + Moon   -------------------------------------*/}

        {/*
          Two nested groups replace the per-frame geometry rebuild:
            Outer group  — latitude tilt (X rotation): tilts the celestial pole to the correct elevation.
                           Only changes when lat changes, which is rare.
            Inner group  — LST rotation (Y rotation): spins the whole sphere as time advances.
                           This is the only thing that changes when the time slider moves — no geometry
                           is touched, Three.js just updates a single matrix.
        */}
        <group ref={skyGroupRef} rotation={[latTiltRad, 0, 0]}>
          <group rotation={[0, -lst, 0]}>
            <StarField
              positions={positions}
              alphas={alphas}
              starMap={starMap}
              onStarClick={onStarClick}
              groupRef={skyGroupRef}
            />
            <sprite position={[moonX, moonY, moonZ]} scale={[3, 3, 1]}>
              <spriteMaterial map={moonTexture} transparent />
            </sprite>
          </group>
        </group>
        {/*---------------------------------   Ground   -------------------------------------*/}

        <mesh position={[0, -1.5, 0]} rotation={[Math.PI, 0, 0]}>
          <sphereGeometry
            args={[10, 32, 32, 0, Math.PI * 2, 0, Math.PI * 0.5]}
          />
          <meshStandardMaterial
            color="#222"
            roughness={1}
            metalness={0}
            side={THREE.DoubleSide}
          />
        </mesh>

        {/*---------------------------------   Camera Controls   -------------------------------------*/}

        <CameraControls
          ref={controlsRef}
          //disabling zoom https://discourse.threejs.org/t/is-it-possible-to-disable-the-zooming-of-cameracontrols-react-three-drei/67476/4
          minZoom={0}
          maxZoom={0}
          minDistance={0.5}
          maxDistance={2.5}
          minPolarAngle={Math.PI * 0.5}
          maxPolarAngle={Math.PI * 0.9}

          //disables the right click movement.
          mouseButtons={{
            left: 1,
            middle: 1,
            wheel: 1,
            right: 0,
          }}
        />

        {/*---------------------------------   Direction Indicator  -------------------------------------*/}

        <Html position={[0, -3, -10]}>
          <div style={{ color: "white", fontSize: "16px", opacity: 0.5 }}>
            S
          </div>
        </Html>
        <Html position={[10, -3, 0]}>
          <div style={{ color: "white", fontSize: "16px", opacity: 0.5 }}>
            W
          </div>
        </Html>
        <Html position={[0, -3, 10]}>
          <div style={{ color: "white", fontSize: "16px", opacity: 0.5 }}>
            N
          </div>
        </Html>
        <Html position={[-10, -3, 0]}>
          <div style={{ color: "white", fontSize: "16px", opacity: 0.5 }}>
            E
          </div>
        </Html>
      </Canvas>
    </>
  );
}